
micronaut:
  application:
    name: UsersServices
  server:
    port: 8888
---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${APPFACTORY_JWT_SECRET:X4Tc6Qa5Cr<6xt{eZ/3AC93|B5iF]0;G0vH+AT=g*{5/_93)q,*M[T8Jbispbd5vb6S-4[f^}

      writer:
        header:
          enabled: true
          headerName: "Authorization" 
          prefix: "Bearer "
      propagation:
        enabled: true
        service-id-regex: "offers-services|requests-services|gateway"

      
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
jackson:
  bean-introspection-module: true
---
datasources:
  users:
    url: jdbc:mysql://127.0.0.1:3306/helloworlddb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL

---
liquibase:
  datasources:
    users:
      change-log: 'classpath:db/liquibase-changelog.xml'

